"""add_terms_and_conditions

Revision ID: 1c9ab1b72be0
Revises: 4be4b1152694
Create Date: 2026-01-16 10:45:13.862493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c9ab1b72be0'
down_revision: Union[str, None] = '4be4b1152694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terms_acceptances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tcs_version', sa.String(length=20), nullable=False),
    sa.Column('tcs_document_url', sa.Text(), nullable=False),
    sa.Column('tcs_document_hash', sa.String(length=64), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('acceptance_method', sa.String(length=50), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('declined_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_terms_acceptance_company', 'terms_acceptances', ['company_id'], unique=False)
    op.create_index('idx_terms_acceptance_job', 'terms_acceptances', ['job_id'], unique=False)
    op.create_index(op.f('ix_terms_acceptances_company_id'), 'terms_acceptances', ['company_id'], unique=False)
    op.create_index(op.f('ix_terms_acceptances_created_at'), 'terms_acceptances', ['created_at'], unique=False)
    op.create_index(op.f('ix_terms_acceptances_job_id'), 'terms_acceptances', ['job_id'], unique=False)
    op.add_column('companies', sa.Column('tcs_document_url', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('tcs_version', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('tcs_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('companies', sa.Column('tcs_document_hash', sa.String(length=64), nullable=True))
    op.add_column('companies', sa.Column('tcs_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'tcs_enabled')
    op.drop_column('companies', 'tcs_document_hash')
    op.drop_column('companies', 'tcs_updated_at')
    op.drop_column('companies', 'tcs_version')
    op.drop_column('companies', 'tcs_document_url')
    op.drop_index(op.f('ix_terms_acceptances_job_id'), table_name='terms_acceptances')
    op.drop_index(op.f('ix_terms_acceptances_created_at'), table_name='terms_acceptances')
    op.drop_index(op.f('ix_terms_acceptances_company_id'), table_name='terms_acceptances')
    op.drop_index('idx_terms_acceptance_job', table_name='terms_acceptances')
    op.drop_index('idx_terms_acceptance_company', table_name='terms_acceptances')
    op.drop_table('terms_acceptances')
    # ### end Alembic commands ###
