"""initial_schema

Revision ID: 72e5e19b186d
Revises: 
Create Date: 2025-12-31 22:51:03.898002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72e5e19b186d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bids',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('marketplace_job_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('estimated_duration_hours', sa.Integer(), nullable=True),
    sa.Column('crew_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_generated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marketplace_job_id'], ['marketplace_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bids_job_company', 'bids', ['marketplace_job_id', 'company_id'], unique=False)
    op.create_index(op.f('ix_bids_company_id'), 'bids', ['company_id'], unique=False)
    op.create_index(op.f('ix_bids_expires_at'), 'bids', ['expires_at'], unique=False)
    op.create_index(op.f('ix_bids_marketplace_job_id'), 'bids', ['marketplace_job_id'], unique=False)
    op.create_index(op.f('ix_bids_status'), 'bids', ['status'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('subscription_status', sa.String(length=50), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_index(op.f('ix_companies_stripe_customer_id'), 'companies', ['stripe_customer_id'], unique=True)
    op.create_index(op.f('ix_companies_subscription_status'), 'companies', ['subscription_status'], unique=False)
    op.create_table('marketplace_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pickup', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dropoff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pickup_city', sa.String(length=100), nullable=True),
    sa.Column('dropoff_city', sa.String(length=100), nullable=True),
    sa.Column('property_type', sa.String(length=100), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('total_cbm', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_weight_kg', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('inventory_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('broadcast_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('awarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('winning_company_id', sa.UUID(), nullable=True),
    sa.Column('winning_bid_id', sa.UUID(), nullable=True),
    sa.Column('final_price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('commission_rate', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('commission_amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('commission_paid', sa.Boolean(), nullable=True),
    sa.Column('commission_paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('broadcast_radius_miles', sa.Integer(), nullable=True),
    sa.Column('bid_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['winning_bid_id'], ['bids.id'], ),
    sa.ForeignKeyConstraint(['winning_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_marketplace_jobs_location', 'marketplace_jobs', ['pickup_city', 'status'], unique=False)
    op.create_index('idx_marketplace_jobs_status', 'marketplace_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_marketplace_jobs_commission_paid'), 'marketplace_jobs', ['commission_paid'], unique=False)
    op.create_index(op.f('ix_marketplace_jobs_customer_email'), 'marketplace_jobs', ['customer_email'], unique=False)
    op.create_index(op.f('ix_marketplace_jobs_dropoff_city'), 'marketplace_jobs', ['dropoff_city'], unique=False)
    op.create_index(op.f('ix_marketplace_jobs_pickup_city'), 'marketplace_jobs', ['pickup_city'], unique=False)
    op.create_index(op.f('ix_marketplace_jobs_status'), 'marketplace_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_marketplace_jobs_submitted_at'), 'marketplace_jobs', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_marketplace_jobs_token'), 'marketplace_jobs', ['token'], unique=True)
    op.create_table('commissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('marketplace_job_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('job_price', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('commission_rate', sa.DECIMAL(precision=5, scale=4), nullable=False),
    sa.Column('commission_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('stripe_charge_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_transfer_id', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['marketplace_job_id'], ['marketplace_jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_charge_id')
    )
    op.create_index(op.f('ix_commissions_company_id'), 'commissions', ['company_id'], unique=False)
    op.create_index(op.f('ix_commissions_marketplace_job_id'), 'commissions', ['marketplace_job_id'], unique=False)
    op.create_index(op.f('ix_commissions_status'), 'commissions', ['status'], unique=False)
    op.create_table('job_broadcasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('marketplace_job_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notification_method', sa.String(length=50), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bid_submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marketplace_job_id'], ['marketplace_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_broadcasts_job_company', 'job_broadcasts', ['marketplace_job_id', 'company_id'], unique=False)
    op.create_index(op.f('ix_job_broadcasts_company_id'), 'job_broadcasts', ['company_id'], unique=False)
    op.create_index(op.f('ix_job_broadcasts_marketplace_job_id'), 'job_broadcasts', ['marketplace_job_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pickup', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dropoff', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('property_type', sa.String(length=100), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('total_cbm', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_weight_kg', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('custom_price_low', sa.Integer(), nullable=True),
    sa.Column('custom_price_high', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jobs_company_status', 'jobs', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_jobs_company_id'), 'jobs', ['company_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_submitted_at'), 'jobs', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_jobs_token'), 'jobs', ['token'], unique=True)
    op.create_table('marketplace_rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('marketplace_job_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['marketplace_job_id'], ['marketplace_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_rooms_marketplace_job_id'), 'marketplace_rooms', ['marketplace_job_id'], unique=False)
    op.create_table('pricing_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('price_per_cbm', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('callout_fee', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('bulky_item_fee', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('fragile_item_fee', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('weight_threshold_kg', sa.Integer(), nullable=True),
    sa.Column('price_per_kg_over_threshold', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('base_distance_km', sa.Integer(), nullable=True),
    sa.Column('price_per_km', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('estimate_low_multiplier', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('estimate_high_multiplier', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_configs_company_id'), 'pricing_configs', ['company_id'], unique=True)
    op.create_table('stripe_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stripe_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripe_events_company_id'), 'stripe_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_stripe_events_event_type'), 'stripe_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_stripe_events_processed'), 'stripe_events', ['processed'], unique=False)
    op.create_index(op.f('ix_stripe_events_stripe_event_id'), 'stripe_events', ['stripe_event_id'], unique=True)
    op.create_table('usage_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_cost_usd', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analytics_company_date', 'usage_analytics', ['company_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_usage_analytics_company_id'), 'usage_analytics', ['company_id'], unique=False)
    op.create_index(op.f('ix_usage_analytics_event_type'), 'usage_analytics', ['event_type'], unique=False)
    op.create_index(op.f('ix_usage_analytics_recorded_at'), 'usage_analytics', ['recorded_at'], unique=False)
    op.create_table('user_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('job_token', sa.String(length=50), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('page_url', sa.String(length=500), nullable=False),
    sa.Column('element_id', sa.String(length=200), nullable=True),
    sa.Column('element_text', sa.String(length=200), nullable=True),
    sa.Column('time_spent_seconds', sa.Float(), nullable=True),
    sa.Column('scroll_depth_percent', sa.Integer(), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('screen_width', sa.Integer(), nullable=True),
    sa.Column('screen_height', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('interaction_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_interactions_company_id'), 'user_interactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_user_interactions_event_type'), 'user_interactions', ['event_type'], unique=False)
    op.create_index(op.f('ix_user_interactions_id'), 'user_interactions', ['id'], unique=False)
    op.create_index(op.f('ix_user_interactions_job_token'), 'user_interactions', ['job_token'], unique=False)
    op.create_index(op.f('ix_user_interactions_recorded_at'), 'user_interactions', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_user_interactions_session_id'), 'user_interactions', ['session_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_company_email', 'users', ['company_id', 'email'], unique=True)
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('admin_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_notes_created_at'), 'admin_notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_notes_job_id'), 'admin_notes', ['job_id'], unique=False)
    op.create_table('marketplace_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('marketplace_room_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('length_cm', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('width_cm', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('height_cm', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('weight_kg', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('cbm', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('bulky', sa.Boolean(), nullable=True),
    sa.Column('fragile', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['marketplace_room_id'], ['marketplace_rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_items_marketplace_room_id'), 'marketplace_items', ['marketplace_room_id'], unique=False)
    op.create_table('marketplace_photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('marketplace_room_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['marketplace_room_id'], ['marketplace_rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_photos_marketplace_room_id'), 'marketplace_photos', ['marketplace_room_id'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_job_id'), 'rooms', ['job_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('length_cm', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('width_cm', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('height_cm', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('weight_kg', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('cbm', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('bulky', sa.Boolean(), nullable=True),
    sa.Column('fragile', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_room_id'), 'items', ['room_id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_room_id'), 'photos', ['room_id'], unique=False)
    op.create_table('ai_item_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('predicted_length_cm', sa.Float(), nullable=True),
    sa.Column('predicted_width_cm', sa.Float(), nullable=True),
    sa.Column('predicted_height_cm', sa.Float(), nullable=True),
    sa.Column('predicted_weight_kg', sa.Float(), nullable=True),
    sa.Column('predicted_cbm', sa.Float(), nullable=True),
    sa.Column('predicted_bulky', sa.Boolean(), nullable=True),
    sa.Column('predicted_fragile', sa.Boolean(), nullable=True),
    sa.Column('was_accepted', sa.Boolean(), nullable=True),
    sa.Column('was_manually_corrected', sa.Boolean(), nullable=True),
    sa.Column('corrected_to_item_name', sa.String(length=200), nullable=True),
    sa.Column('corrected_by_user_id', sa.UUID(), nullable=True),
    sa.Column('correction_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_model_version', sa.String(length=50), nullable=True),
    sa.Column('ai_processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corrected_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_item_predictions_created_at'), 'ai_item_predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_item_predictions_id'), 'ai_item_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_ai_item_predictions_photo_id'), 'ai_item_predictions', ['photo_id'], unique=False)
    op.create_index(op.f('ix_ai_item_predictions_room_id'), 'ai_item_predictions', ['room_id'], unique=False)
    op.create_index(op.f('ix_ai_item_predictions_was_accepted'), 'ai_item_predictions', ['was_accepted'], unique=False)
    op.create_index(op.f('ix_ai_item_predictions_was_manually_corrected'), 'ai_item_predictions', ['was_manually_corrected'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_item_predictions_was_manually_corrected'), table_name='ai_item_predictions')
    op.drop_index(op.f('ix_ai_item_predictions_was_accepted'), table_name='ai_item_predictions')
    op.drop_index(op.f('ix_ai_item_predictions_room_id'), table_name='ai_item_predictions')
    op.drop_index(op.f('ix_ai_item_predictions_photo_id'), table_name='ai_item_predictions')
    op.drop_index(op.f('ix_ai_item_predictions_id'), table_name='ai_item_predictions')
    op.drop_index(op.f('ix_ai_item_predictions_created_at'), table_name='ai_item_predictions')
    op.drop_table('ai_item_predictions')
    op.drop_index(op.f('ix_photos_room_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_items_room_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_rooms_job_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_marketplace_photos_marketplace_room_id'), table_name='marketplace_photos')
    op.drop_table('marketplace_photos')
    op.drop_index(op.f('ix_marketplace_items_marketplace_room_id'), table_name='marketplace_items')
    op.drop_table('marketplace_items')
    op.drop_index(op.f('ix_admin_notes_job_id'), table_name='admin_notes')
    op.drop_index(op.f('ix_admin_notes_created_at'), table_name='admin_notes')
    op.drop_table('admin_notes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_index('idx_users_company_email', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_interactions_session_id'), table_name='user_interactions')
    op.drop_index(op.f('ix_user_interactions_recorded_at'), table_name='user_interactions')
    op.drop_index(op.f('ix_user_interactions_job_token'), table_name='user_interactions')
    op.drop_index(op.f('ix_user_interactions_id'), table_name='user_interactions')
    op.drop_index(op.f('ix_user_interactions_event_type'), table_name='user_interactions')
    op.drop_index(op.f('ix_user_interactions_company_id'), table_name='user_interactions')
    op.drop_table('user_interactions')
    op.drop_index(op.f('ix_usage_analytics_recorded_at'), table_name='usage_analytics')
    op.drop_index(op.f('ix_usage_analytics_event_type'), table_name='usage_analytics')
    op.drop_index(op.f('ix_usage_analytics_company_id'), table_name='usage_analytics')
    op.drop_index('idx_analytics_company_date', table_name='usage_analytics')
    op.drop_table('usage_analytics')
    op.drop_index(op.f('ix_stripe_events_stripe_event_id'), table_name='stripe_events')
    op.drop_index(op.f('ix_stripe_events_processed'), table_name='stripe_events')
    op.drop_index(op.f('ix_stripe_events_event_type'), table_name='stripe_events')
    op.drop_index(op.f('ix_stripe_events_company_id'), table_name='stripe_events')
    op.drop_table('stripe_events')
    op.drop_index(op.f('ix_pricing_configs_company_id'), table_name='pricing_configs')
    op.drop_table('pricing_configs')
    op.drop_index(op.f('ix_marketplace_rooms_marketplace_job_id'), table_name='marketplace_rooms')
    op.drop_table('marketplace_rooms')
    op.drop_index(op.f('ix_jobs_token'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_submitted_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company_id'), table_name='jobs')
    op.drop_index('idx_jobs_company_status', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_job_broadcasts_marketplace_job_id'), table_name='job_broadcasts')
    op.drop_index(op.f('ix_job_broadcasts_company_id'), table_name='job_broadcasts')
    op.drop_index('idx_broadcasts_job_company', table_name='job_broadcasts')
    op.drop_table('job_broadcasts')
    op.drop_index(op.f('ix_commissions_status'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_marketplace_job_id'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_company_id'), table_name='commissions')
    op.drop_table('commissions')
    op.drop_index(op.f('ix_marketplace_jobs_token'), table_name='marketplace_jobs')
    op.drop_index(op.f('ix_marketplace_jobs_submitted_at'), table_name='marketplace_jobs')
    op.drop_index(op.f('ix_marketplace_jobs_status'), table_name='marketplace_jobs')
    op.drop_index(op.f('ix_marketplace_jobs_pickup_city'), table_name='marketplace_jobs')
    op.drop_index(op.f('ix_marketplace_jobs_dropoff_city'), table_name='marketplace_jobs')
    op.drop_index(op.f('ix_marketplace_jobs_customer_email'), table_name='marketplace_jobs')
    op.drop_index(op.f('ix_marketplace_jobs_commission_paid'), table_name='marketplace_jobs')
    op.drop_index('idx_marketplace_jobs_status', table_name='marketplace_jobs')
    op.drop_index('idx_marketplace_jobs_location', table_name='marketplace_jobs')
    op.drop_table('marketplace_jobs')
    op.drop_index(op.f('ix_companies_subscription_status'), table_name='companies')
    op.drop_index(op.f('ix_companies_stripe_customer_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_bids_status'), table_name='bids')
    op.drop_index(op.f('ix_bids_marketplace_job_id'), table_name='bids')
    op.drop_index(op.f('ix_bids_expires_at'), table_name='bids')
    op.drop_index(op.f('ix_bids_company_id'), table_name='bids')
    op.drop_index('idx_bids_job_company', table_name='bids')
    op.drop_table('bids')
    # ### end Alembic commands ###
